"""Generator2 LDF rendering."""

from __future__ import annotations

from math import floor

from .context import _Level
from .map_builder import Generator2MapBuilder
from ..constants import GENERATOR2_FACTION_IDS, GENERATOR2_SKIES
from ..ldf import LDFWriter


class Generator2Renderer:
    def __init__(self, map_builder: Generator2MapBuilder) -> None:
        self._map_builder = map_builder

    def _write_level(self, level: _Level) -> str:
        writer = LDFWriter(property_style="php")
        self._write_header(writer, level)
        self._write_beam_gates(writer, level)
        self._write_player_station(writer, level)
        self._write_enemy_stations(writer, level)
        self._write_bombs(writer, level)
        self._write_squads(writer, level)
        self._write_prototypes(writer, level)
        self._write_maps(writer, level)
        return writer.getvalue()

    def _write_header(self, writer: LDFWriter, level: _Level) -> None:
        writer.line(";#*+ don't edit the magic runes")
        writer.line("")
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Generated by Urban Assault Level Generator           ---")
        writer.line(";--- Generator: Generator2 (PHP-derived port)             ---")
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Generation Parameters:")
        writer.line(f";--- Seed: {level.seed}")
        writer.line(f";--- Level ID: {level.level_id}")
        writer.line(f";--- Tileset: {level.tileset}")
        writer.line(f";--- Map Size: {level.width}x{level.height}")
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Main Level Info                                      ---")
        writer.line(";------------------------------------------------------------")
        writer.line("begin_level")
        writer.property("set", level.tileset)
        writer.property("sky", f"objects/{level.rng.choice(GENERATOR2_SKIES)}.base")
        for slot, palette in enumerate(["standard", "red", "blau", "gruen", "inverse", "invdark", "sw", "invtuerk"]):
            writer.property(f"slot{slot}", f"palette/{palette}.pal")
        writer.end_block()
        writer.line("")
        writer.line("; Mission Briefing Map")
        writer.line("begin_mbmap")
        writer.property("name", level.mission_briefing_map)
        writer.end_block()
        writer.line("")
        writer.line("; Mission Debriefing Map")
        writer.line("begin_dbmap")
        writer.property("name", level.mission_debriefing_map)
        writer.end_block()
        writer.line("")

    def _write_beam_gates(self, writer: LDFWriter, level: _Level) -> None:
        writer.line("; Beam Gates")
        for gate in level.gates:
            writer.line("")
            writer.line("begin_gate")
            writer.property("sec_x", gate["x"])
            writer.property("sec_y", gate["y"])
            writer.property("closed_bp", 5)
            writer.property("opened_bp", 6)
            for target in gate["targets"]:
                writer.property("target_level", target)
            for _ in range(6):
                if level.rng.rand_range(0, 1):
                    writer.property("keysec_x", self._map_builder._random_x(level))
                    writer.property("keysec_y", self._map_builder._random_y(level))
            writer.property("mb_status", "unknown")
            writer.end_block()
        writer.line("")

    def _write_player_station(self, writer: LDFWriter, level: _Level) -> None:
        station = level.hosts[level.player_faction][0]
        energy = level.rng.rand_range(6, 10) * 100000
        reload_const = floor((((energy - 550000) / 4) + 550000) / 5)
        writer.line("; Player Host Station")
        writer.line("")
        writer.line("begin_robo")
        writer.property("owner", GENERATOR2_FACTION_IDS[level.player_faction])
        writer.property("vehicle", level.player_vehicle)
        writer.property("pos_x", self._map_builder._get_position(station["x"]))
        writer.property("pos_y", level.rng.rand_range(20, 45) * -10)
        writer.property("pos_z", self._map_builder._get_position(station["y"], vertical=True))
        writer.property("energy", energy)
        writer.property("reload_const", reload_const)
        writer.end_block()
        writer.line("")
        writer.line("; Enemy Host Stations")

    def _write_enemy_stations(self, writer: LDFWriter, level: _Level) -> None:
        for faction in level.hosts:
            if faction == level.player_faction:
                continue
            for station in level.hosts[faction]:
                energy = level.rng.rand_range(8, 22) * 100000
                reload_const = floor(((energy - 500000) / 3) + 500000)
                host_vehicle = level.host_vehicles.get(faction, 57)
                if faction == "gho":
                    host_vehicle = 57 if level.rng.rand_range(0, 2) != 0 else 59
                writer.line("")
                writer.line("begin_robo")
                writer.property("owner", GENERATOR2_FACTION_IDS[faction])
                writer.property("vehicle", host_vehicle)
                writer.property("pos_x", self._map_builder._get_position(station["x"]))
                writer.property("pos_y", level.rng.rand_range(20, 45) * -10)
                writer.property("pos_z", self._map_builder._get_position(station["y"], vertical=True))
                writer.property("energy", energy)
                writer.property("reload_const", reload_const)
                if level.rng.rand_range(0, 1) == 0:
                    writer.property("mb_status", "unknown")
                writer.property("con_budget", level.rng.rand_range(80, 90))
                writer.property("con_delay", level.rng.rand_range(0, 300) * 1000)
                writer.property("def_budget", level.rng.rand_range(70, 100))
                writer.property("def_delay", level.rng.rand_range(0, 300) * 1000)
                writer.property("rec_budget", level.rng.rand_range(50, 80))
                writer.property("rec_delay", level.rng.rand_range(0, 300) * 1000)
                writer.property("rob_budget", level.rng.rand_range(50, 90))
                writer.property("rob_delay", level.rng.rand_range(0, 300) * 1000)
                writer.property("pow_budget", level.rng.rand_range(40, 70))
                writer.property("pow_delay", level.rng.rand_range(0, 300) * 1000)
                writer.property("rad_budget", level.rng.rand_range(0, 10))
                writer.property("rad_delay", level.rng.rand_range(600, 1800) * 1000)
                writer.property("saf_budget", level.rng.rand_range(50, 100))
                writer.property("saf_delay", level.rng.rand_range(0, 300) * 1000)
                writer.property("cpl_budget", level.rng.rand_range(30, 50))
                writer.property("cpl_delay", level.rng.rand_range(0, 300) * 1000)
                writer.end_block()

    def _write_bombs(self, writer: LDFWriter, level: _Level) -> None:
        writer.line("")
        writer.line("; Stoudson Bomb")
        for bomb in level.bombs:
            writer.line("")
            writer.line("begin_item")
            writer.property("sec_x", bomb["x"])
            writer.property("sec_y", bomb["y"])
            writer.property("inactive_bp", 68 if level.tileset == 6 else 35)
            writer.property("active_bp", 69 if level.tileset == 6 else 36)
            writer.property("trigger_bp", 70 if level.tileset == 6 else 36)
            writer.property("type", 1)
            writer.property("countdown", bomb["timeout"])
            for key in bomb["keys"]:
                writer.property("keysec_x", key["x"])
                writer.property("keysec_y", key["y"])
            writer.end_block()
        writer.line("")

    def _write_squads(self, writer: LDFWriter, level: _Level) -> None:
        writer.line(";Predefined Squad")
        for squad in level.squads:
            writer.line("")
            writer.line("begin_squad")
            writer.property("owner", GENERATOR2_FACTION_IDS[squad["faction"]])
            writer.property("vehicle", squad["vehicle"])
            writer.property("num", squad["num"])
            writer.property("pos_x", self._map_builder._get_position(squad["x"]))
            writer.property("pos_z", self._map_builder._get_position(squad["y"], vertical=True))
            writer.end_block()
        writer.line("")

    def _write_prototypes(self, writer: LDFWriter, level: _Level) -> None:
        writer.line("; Prototype Modifications")
        writer.line("")
        writer.line("include data:scripts/startup2.scr")
        for faction in self._map_builder._present_factions(level):
            writer.line("")
            writer.line(f"begin_enable {GENERATOR2_FACTION_IDS[faction]}")
            for vehicle in level.vehicles_by_faction[faction]:
                writer.property("vehicle", vehicle)
            for building in level.buildings_by_faction[faction]:
                writer.property("building", building)
            writer.end_block()
        writer.line("")

    def _write_maps(self, writer: LDFWriter, level: _Level) -> None:
        writer.line("begin_maps")
        for map_name in ("typ", "own", "hgt", "blg"):
            writer.map_block(f"{map_name}_map", level.maps[map_name], level.width, level.height, php_style=True)
        writer.end_block()
