"""Generator3 LDF rendering (tab style, matching the authored originals)."""

from __future__ import annotations

from typing import Any

from ..constants import FACTION_NAMES
from ..ldf import LDFWriter
from .context import _Gen3Level

_PALETTE_SLOTS = ["standard", "red", "blau", "gruen", "inverse", "invdark", "sw", "invtuerk"]

_ROBO_KEY_ORDER = (
    "owner", "vehicle", "pos_x", "pos_y", "pos_z", "energy", "reload_const", "viewangle", "mb_status",
    "con_budget", "con_delay", "def_budget", "def_delay", "rec_budget", "rec_delay",
    "rob_budget", "rob_delay", "pow_budget", "pow_delay", "rad_budget", "rad_delay",
    "saf_budget", "saf_delay", "cpl_budget", "cpl_delay",
)

_HEADER_PASSTHROUGH = ("title_deutsch", "title_english", "ambiencetrack", "event_loop", "movie", "win_movie", "lose_movie")


class Generator3Renderer:
    def write(self, level: _Gen3Level) -> str:
        writer = LDFWriter(property_style="tabs")
        self._write_header(writer, level)
        self._write_briefing_maps(writer, level)
        self._write_gates(writer, level)
        self._write_robos(writer, level)
        self._write_squads(writer, level)
        self._write_prototype(writer, level)
        self._write_enables(writer, level)
        self._write_gems(writer, level)
        self._write_items(writer, level)
        self._write_maps(writer, level)
        return writer.getvalue()

    def _write_header(self, writer: LDFWriter, level: _Gen3Level) -> None:
        writer.line(";#*+ don't edit the magic runes")
        writer.line("")
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Generated by Urban Assault Level Generator           ---")
        writer.line(";--- Generator: Generator3 (Remix, corpus-driven)         ---")
        writer.line(";------------------------------------------------------------")
        writer.line(f";--- Seed: {level.seed}")
        writer.line(f";--- Skeleton: {level.skeleton.name} ({level.skeleton.source})")
        writer.line(f";--- Profile: {level.profile_id}")
        writer.line(f";--- Map Size: {level.width}x{level.height}  Tileset: {level.tileset}")
        writer.line(";------------------------------------------------------------")
        writer.begin_block("begin_level")
        writer.property("set", level.tileset)
        writer.property("sky", level.sky)
        for slot, palette in enumerate(_PALETTE_SLOTS):
            writer.property(f"slot{slot}", f"palette/{palette}.pal")
        writer.property("title_default", level.header.get("title_default", level.skeleton.name))
        for key in _HEADER_PASSTHROUGH:
            if level.header.get(key) is not None:
                writer.property(key, level.header[key])
        writer.end_block()
        writer.line("")

    def _write_briefing_maps(self, writer: LDFWriter, level: _Gen3Level) -> None:
        skeleton_mb = level.skeleton.record.get("mbmap", {})
        skeleton_db = level.skeleton.record.get("dbmap", {})
        writer.begin_block("begin_mbmap")
        writer.property("name", level.mission_briefing_map)
        self._write_map_size(writer, skeleton_mb)
        writer.end_block()
        writer.begin_block("begin_dbmap")
        writer.property("name", level.mission_debriefing_map)
        self._write_map_size(writer, skeleton_db)
        writer.end_block()
        writer.line("")

    @staticmethod
    def _write_map_size(writer: LDFWriter, block: dict[str, Any]) -> None:
        for key in ("size_x", "size_y"):
            if block.get(key) is not None:
                writer.property(key, block[key])

    def _write_gates(self, writer: LDFWriter, level: _Gen3Level) -> None:
        for gate in level.gates:
            writer.begin_block("begin_gate")
            writer.property("sec_x", gate["sec_x"])
            writer.property("sec_y", gate["sec_y"])
            writer.property("closed_bp", gate.get("closed_bp", 5))
            writer.property("opened_bp", gate.get("opened_bp", 6))
            for target in gate.get("targets", []):
                writer.property("target_level", target)
            for key in gate.get("keysecs", []):
                writer.property("keysec_x", key["x"])
                writer.property("keysec_y", key["y"])
            if gate.get("mb_status") is not None:
                writer.property("mb_status", gate["mb_status"])
            writer.end_block()
            writer.line("")

    def _write_robos(self, writer: LDFWriter, level: _Gen3Level) -> None:
        for robo in level.robos:
            owner = robo.get("owner")
            writer.line(f"; Host Station ({FACTION_NAMES.get(int(owner), owner)})")
            writer.begin_block("begin_robo")
            for key in _ROBO_KEY_ORDER:
                if key in robo and robo[key] is not None:
                    writer.property(key, robo[key])
            writer.end_block()
            writer.line("")

    def _write_squads(self, writer: LDFWriter, level: _Gen3Level) -> None:
        for squad in level.squads:
            writer.begin_block("begin_squad")
            writer.property("owner", squad["owner"])
            writer.property("vehicle", squad["vehicle"])
            writer.property("num", squad["num"])
            writer.property("pos_x", squad["pos_x"])
            writer.property("pos_z", squad["pos_z"])
            if squad.get("mb_status") is not None:
                writer.property("mb_status", squad["mb_status"])
            if squad.get("useable"):
                writer.line("\tuseable")
            writer.end_block()
        writer.line("")

    def _write_prototype(self, writer: LDFWriter, level: _Gen3Level) -> None:
        for line in level.prototype:
            writer.line(line)
        writer.line("")

    def _write_enables(self, writer: LDFWriter, level: _Gen3Level) -> None:
        for enable in level.enables:
            writer.begin_block(f"begin_enable {enable['owner']}")
            for vehicle in enable.get("vehicles", []):
                writer.property("vehicle", vehicle)
            for building in enable.get("buildings", []):
                writer.property("building", building)
            writer.end_block()
            writer.line("")

    def _write_gems(self, writer: LDFWriter, level: _Gen3Level) -> None:
        for gem in level.gems:
            for line in gem:
                writer.line(line)
            writer.line("")

    def _write_items(self, writer: LDFWriter, level: _Gen3Level) -> None:
        for item in level.items:
            writer.begin_block("begin_item")
            for key in ("sec_x", "sec_y", "inactive_bp", "active_bp", "trigger_bp", "type", "countdown"):
                if item.get(key) is not None:
                    writer.property(key, item[key])
            for key in item.get("keysecs", []):
                writer.property("keysec_x", key["x"])
                writer.property("keysec_y", key["y"])
            writer.end_block()
            writer.line("")

    def _write_maps(self, writer: LDFWriter, level: _Gen3Level) -> None:
        writer.begin_block("begin_maps")
        for name in ("typ", "own", "hgt", "blg"):
            writer.map_block(f"{name}_map", level.maps[name], level.width, level.height)
        writer.end_block()
