"""Generator1 LDF rendering."""

from __future__ import annotations

from .context import _State
from .map_builder import Generator1MapBuilder
from .scenario import Generator1ScenarioPlanner
from .tables import (
    TECH_UPGRADE_BUILDING_IDS_BY_TYPE,
    TECH_UPGRADE_BUILDING_TILESETS,
    TECH_UPGRADE_BUILDING_TYP_BY_ID,
)
from ..constants import (
    BUILDINGS_PLAYER_IDS,
    BUILDINGS_PLAYER_PROBABILITIES,
    FACTION_BLACK_SECT,
    FACTION_PLAYER,
    FACTION_SULGOGARS,
    FACTION_TUTOR,
    HOST_VEHICLE_BY_FACTION,
    SKY_OPTIONS,
    VEHICLES_PLAYER_IDS,
    VEHICLES_PLAYER_PROBABILITIES,
    sector_to_world_x,
    sector_to_world_z,
)
from ..ldf import LDFWriter


_ROCK_SLED_VEHICLE_ID = 11
_METROPOLIS_DAWN_PROFILE_IDS = {"md-ghorkov", "md-taerkasten"}
_ROCK_SLED_EXCLUDED_CAMPAIGN_FACTIONS = {FACTION_BLACK_SECT}


class Generator1Renderer:
    def __init__(self, scenario: Generator1ScenarioPlanner, map_builder: Generator1MapBuilder) -> None:
        self._scenario = scenario
        self._map_builder = map_builder

    def _write_level(self, state: _State) -> str:
        writer = LDFWriter(property_style="tabs")
        self._write_header(writer, state)
        self._write_brief_maps(writer, state)
        self._map_builder._seed_beam_gate_keys(state)
        self._write_beam_gate(writer, state)
        self._write_superitems(writer, state)
        self._write_robos(writer, state)
        self._write_include_and_enables(writer, state)
        self._write_tech_upgrades(writer, state)
        self._write_maps(writer, state)
        return writer.getvalue()

    def _write_header(self, writer: LDFWriter, state: _State) -> None:
        writer.line(";#*+ don't edit the magic runes")
        writer.line("")
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Generated by Urban Assault Level Generator           ---")
        writer.line(";--- Generator: Generator1                                ---")
        writer.line(";------------------------------------------------------------")
        writer.line("begin_level")
        writer.property("set", state.tileset)
        writer.property("sky", f"objects/{state.rng.choice(SKY_OPTIONS)}")
        writer.property("slot0", "palette/standard.pal")
        writer.property("slot1", "palette/red.pal")
        writer.property("slot2", "palette/blau.pal")
        writer.property("slot3", "palette/gruen.pal")
        writer.property("slot4", "palette/inverse.pal")
        writer.property("slot5", "palette/invdark.pal")
        writer.property("slot6", "palette/sw.pal")
        writer.property("slot7", "palette/invtuerk.pal")
        if state.win_movie:
            writer.property("win_movie", "win.iff")
        if state.lose_movie:
            writer.property("lose_movie", "lose.iff")
        writer.end_block()
        writer.line("")

    def _write_brief_maps(self, writer: LDFWriter, state: _State) -> None:
        writer.line("begin_mbmap")
        writer.property("name", state.mission_briefing_map)
        writer.end_block()
        writer.line("")
        writer.line("begin_dbmap")
        writer.property("name", state.mission_debriefing_map)
        writer.end_block()
        writer.line("")

    def _write_beam_gate(self, writer: LDFWriter, state: _State) -> None:
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Beam Gates                                           ---")
        writer.line(";------------------------------------------------------------")
        writer.line("begin_gate")
        writer.property("sec_x", state.base_x)
        writer.property("sec_y", state.base_y)
        writer.property("closed_bp", 5)
        writer.property("opened_bp", 6)
        targets = state.gate_target_level_ids or [state.gate_target_level_id]
        for target in targets:
            writer.property("target_level", target)
        for x, y in state.gate_keys:
            writer.property("keysec_x", x)
            writer.property("keysec_y", y)
        writer.property("mb_status", "unknown")
        writer.end_block()
        writer.line("")

    def _write_superitems(self, writer: LDFWriter, state: _State) -> None:
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Superitems                                           ---")
        writer.line(";------------------------------------------------------------")
        for item in state.superitems:
            writer.line("begin_item")
            writer.property("sec_x", item["x"])
            writer.property("sec_y", item["y"])
            writer.property("inactive_bp", 35)
            writer.property("active_bp", 36)
            writer.property("trigger_bp", 36)
            writer.property("type", 1)
            writer.property("countdown", item["countdown"])
            for x, y in item["keys"]:
                writer.property("keysec_x", x)
                writer.property("keysec_y", y)
            writer.end_block()
            writer.line("")

    def _write_robos(self, writer: LDFWriter, state: _State) -> None:
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Robo Definitions                                    ---")
        writer.line(";------------------------------------------------------------")
        writer.line("begin_robo")
        writer.property("owner", state.player_faction)
        writer.property(
            "vehicle",
            state.player_host_vehicle_id
            or state.host_vehicle_by_faction.get(state.player_faction)
            or HOST_VEHICLE_BY_FACTION[FACTION_PLAYER],
        )
        writer.property("pos_x", sector_to_world_x(state.player_host_x))
        writer.property("pos_y", -330)
        writer.property("pos_z", sector_to_world_z(state.player_host_y))
        writer.property("energy", state.player_energy)
        writer.property("reload_const", 165625)
        writer.property("viewangle", 23)
        writer.end_block()
        writer.line("")
        for faction in self._scenario.enemy_factions(state):
            for slot in range(3):
                world = state.ai_slot_world[faction][slot]
                if world:
                    energy = state.ai_slot_energy[faction][slot] or self._default_ai_energy(state, faction)
                    self._write_ai_robo(writer, state, faction, slot, world[0], world[1], energy)

    def _write_ai_robo(
        self,
        writer: LDFWriter,
        state: _State,
        faction: int,
        slot: int,
        pos_x: int,
        pos_z: int,
        energy: int,
    ) -> None:
        vehicle = (
            state.ai_slot_host_vehicle_id[faction][slot]
            or state.ai_host_vehicle_id[faction]
            or state.host_vehicle_by_faction.get(faction, 57)
        )
        writer.line("begin_robo")
        writer.property("owner", faction)
        writer.property("vehicle", vehicle)
        writer.property("pos_x", pos_x)
        writer.property("pos_y", -330)
        writer.property("pos_z", pos_z)
        writer.property("energy", energy)
        writer.property("reload_const", 600000)
        self._write_ai_budgets(writer, state, faction)
        writer.end_block()
        writer.line("")

    @staticmethod
    def _default_ai_energy(state: _State, faction: int) -> int:
        if faction == FACTION_TUTOR:
            return 200000
        return 300000 + state.difficulty * 50000

    def _write_ai_budgets(self, writer: LDFWriter, state: _State, faction: int) -> None:
        if faction == FACTION_TUTOR:
            values = {
                "con_budget": 70, "con_delay": 290000, "def_budget": 80, "def_delay": 200000,
                "rec_budget": 80, "rec_delay": 250000, "rob_budget": 80, "rob_delay": 300000,
                "pow_budget": 0, "pow_delay": 0, "rad_budget": 0, "rad_delay": 0,
                "saf_budget": 0, "saf_delay": 0, "cpl_budget": 0, "cpl_delay": 0,
            }
        elif state.difficulty >= 6:
            values = {
                "con_budget": 100, "con_delay": 0, "def_budget": 99, "def_delay": 0,
                "rec_budget": 90, "rec_delay": 0, "rob_budget": 85, "rob_delay": 0,
                "pow_budget": 20, "pow_delay": 0, "rad_budget": 20, "rad_delay": 0,
                "saf_budget": 20, "saf_delay": 0,
            }
        else:
            values = {
                "con_budget": 100, "con_delay": 200, "def_budget": 90, "def_delay": 100,
                "rec_budget": 85, "rec_delay": 50, "rob_budget": 95, "rob_delay": 100000,
                "pow_budget": 20, "pow_delay": 0, "rad_budget": 20, "rad_delay": 0,
                "saf_budget": 20, "saf_delay": 0, "cpl_budget": 80, "cpl_delay": 50000,
            }
        if state.zero_enemy_radar_budgets:
            values["rad_budget"] = 0
        for key, value in values.items():
            writer.property(key, value)
        if faction != FACTION_TUTOR and state.difficulty >= 6:
            writer.property("cpl_delay", 95)
            writer.property("cpl_delay", 0)

    def _write_include_and_enables(self, writer: LDFWriter, state: _State) -> None:
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Prototype Modifications                             ---")
        writer.line(";------------------------------------------------------------")
        writer.line("include data:scripts/startup2.scr")
        writer.line("")
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Prototype Enabling                                   ---")
        writer.line(";------------------------------------------------------------")
        if state.emit_player_enablement:
            self._write_enable_block(writer, state, state.player_faction)
        for faction in self._scenario.enemy_factions(state):
            if any(state.ai_slot_world[faction]):
                self._write_enable_block(writer, state, faction)

    def _write_enable_block(self, writer: LDFWriter, state: _State, faction: int) -> None:
        vehicles, buildings = self._enabled_vehicles(state, faction), self._enabled_buildings(state, faction)
        if not vehicles and not buildings:
            return
        writer.line(f"begin_enable\t{faction}" if faction == state.player_faction else f"begin_enable {faction}")
        for vehicle in vehicles:
            writer.line(f"\tvehicle = {vehicle}")
        for building in buildings:
            writer.line(f"\tbuilding = {building}")
        writer.end_block()
        writer.line("")

    def _enabled_vehicles(self, state: _State, faction: int) -> list[int]:
        if faction in state.forced_enabled_vehicles:
            return list(state.forced_enabled_vehicles[faction])
        if faction == state.player_faction:
            if faction == FACTION_PLAYER:
                enabled = [16, 9]
                self._record_vehicle_flags(state, enabled)
                for vehicle, probability in zip(VEHICLES_PLAYER_IDS, VEHICLES_PLAYER_PROBABILITIES, strict=True):
                    if state.rng.rand_mod(probability) == 0 and vehicle not in enabled:
                        enabled.append(vehicle)
            else:
                candidates = state.vehicles_by_faction.get(faction, [])
                enabled = [vehicle for vehicle in candidates if state.rng.rand_mod(3) == 0] or candidates[:1]
            self._record_vehicle_flags(state, enabled)
            return enabled
        if faction == FACTION_TUTOR:
            return [142]
        if faction == FACTION_SULGOGARS:
            enabled = [73]
            if state.rng.rand_mod(2) == 0:
                enabled.append(71)
            if state.rng.rand_mod(2) == 0:
                enabled.append(72)
            enabled.append(74)
            return enabled
        candidates = state.vehicles_by_faction.get(faction, [])
        enabled = [vehicle for vehicle in candidates if state.rng.rand_mod(3) == 0] or candidates[:1]
        return self._filter_enemy_enabled_vehicles(state, faction, enabled)

    @staticmethod
    def _filter_enemy_enabled_vehicles(state: _State, faction: int, enabled: list[int]) -> list[int]:
        excluded_factions = set(_ROCK_SLED_EXCLUDED_CAMPAIGN_FACTIONS)
        if state.campaign_profile in _METROPOLIS_DAWN_PROFILE_IDS:
            excluded_factions.add(FACTION_PLAYER)
        if not state.generator1_campaign_mode or faction == state.player_faction or faction not in excluded_factions:
            return enabled
        filtered = [vehicle for vehicle in enabled if vehicle != _ROCK_SLED_VEHICLE_ID]
        if filtered or not enabled:
            return filtered
        return [vehicle for vehicle in state.vehicles_by_faction.get(faction, []) if vehicle != _ROCK_SLED_VEHICLE_ID][:1]

    def _enabled_buildings(self, state: _State, faction: int) -> list[int]:
        if faction in state.forced_enabled_buildings:
            return list(state.forced_enabled_buildings[faction])
        if faction == state.player_faction:
            if faction == FACTION_PLAYER:
                enabled = [
                    building
                    for building, probability in zip(BUILDINGS_PLAYER_IDS, BUILDINGS_PLAYER_PROBABILITIES, strict=True)
                    if state.rng.rand_mod(probability) == 0
                ]
            else:
                candidates = state.buildings_by_faction.get(faction, [])
                enabled = [building for building in candidates if state.rng.rand_mod(3) == 0] or candidates[:1]
            self._record_building_flags(state, enabled)
            return enabled
        if faction == FACTION_TUTOR:
            return []
        candidates = state.buildings_by_faction.get(faction, [])
        return [building for building in candidates if state.rng.rand_mod(3) == 0] or candidates[:1]

    @staticmethod
    def _record_vehicle_flags(state: _State, vehicles: list[int]) -> None:
        for vehicle in vehicles:
            if vehicle in state.player_tech_vehicle_ids:
                state.player_vehicle_flags[state.player_tech_vehicle_ids.index(vehicle)] = True

    @staticmethod
    def _record_building_flags(state: _State, buildings: list[int]) -> None:
        for building in buildings:
            if building in state.player_tech_building_ids:
                state.player_building_flags[state.player_tech_building_ids.index(building)] = True

    def _write_tech_upgrades(self, writer: LDFWriter, state: _State) -> None:
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Tech Up-Grades                                       ---")
        writer.line(";------------------------------------------------------------")
        if state.level_index in (3, 43):
            return
        free_cells = self._free_cells(state)
        if not free_cells:
            return
        count = 1 + state.rng.rand_mod(min(5, len(free_cells)))
        for _ in range(count):
            if not free_cells:
                break
            x, y = free_cells.pop(state.rng.rand_mod(len(free_cells)))
            self._write_tech_gem(writer, state, x, y)

    @staticmethod
    def _free_cells(state: _State) -> list[tuple[int, int]]:
        return [
            (x, y)
            for y in range(1, state.height - 1)
            for x in range(1, state.width - 1)
            if state.get("blg", x, y) == 0 and (x, y) not in state.reserved_sectors
        ]

    def _write_tech_gem(self, writer: LDFWriter, state: _State, x: int, y: int) -> None:
        family = state.rng.rand_mod(4)
        upgrade_type = (2, 1, 3, 4)[family]
        building = state.rng.choice(self._tech_upgrade_building_ids(state, upgrade_type))
        state.set("blg", x, y, building)
        state.set("typ", x, y, TECH_UPGRADE_BUILDING_TYP_BY_ID[building])
        if state.get("own", x, y) == state.player_faction:
            state.set("own", x, y, FACTION_TUTOR)
        writer.line("begin_gem")
        writer.property("sec_x", x)
        writer.property("sec_y", y)
        writer.property("building", building)
        writer.property("type", upgrade_type)
        writer.line("begin_action")
        if family == 0:
            vehicle = self._choose_enabled_player_vehicle(state)
            self._write_tech_action(writer, "modify_vehicle", vehicle, {
                "add_energy": 100 + state.rng.rand_mod(401),
                "add_shield": 1 + state.rng.rand_mod(5),
            })
        elif family == 1:
            vehicle = self._choose_enabled_player_vehicle(state)
            self._write_tech_action(writer, "modify_weapon", vehicle, {
                "add_energy": 100 + state.rng.rand_mod(901),
            })
        elif family == 2:
            vehicle = self._unlock_next_vehicle(state)
            self._write_tech_action(writer, "modify_vehicle", vehicle, {"enable": state.player_faction})
        else:
            unlocked_building = self._unlock_next_building(state)
            self._write_tech_action(writer, "modify_building", unlocked_building, {"enable": state.player_faction})
        writer.line("end_action")
        writer.property("mb_status", "unknown")
        writer.end_block()
        writer.line("")

    @staticmethod
    def _write_tech_action(writer: LDFWriter, command: str, target: int, properties: dict[str, int]) -> None:
        writer.line(f"\t{command} {target}")
        for key, value in properties.items():
            writer.property(key, value)
        writer.line("\tend")

    @staticmethod
    def _tech_upgrade_building_ids(state: _State, upgrade_type: int) -> tuple[int, ...]:
        return tuple(
            building
            for building in TECH_UPGRADE_BUILDING_IDS_BY_TYPE[upgrade_type]
            if state.tileset in TECH_UPGRADE_BUILDING_TILESETS.get(building, {state.tileset})
        )

    def _choose_enabled_player_vehicle(self, state: _State) -> int:
        enabled = [
            vehicle for vehicle, flag in zip(state.player_tech_vehicle_ids, state.player_vehicle_flags, strict=True)
            if flag
        ]
        fallback = state.player_tech_vehicle_ids[:1] or [16]
        return state.rng.choice(enabled or fallback)

    def _unlock_next_vehicle(self, state: _State) -> int:
        for i, flag in enumerate(state.player_vehicle_flags):
            if not flag:
                state.player_vehicle_flags[i] = True
                return state.player_tech_vehicle_ids[i]
        return self._choose_enabled_player_vehicle(state)

    def _unlock_next_building(self, state: _State) -> int:
        for i, flag in enumerate(state.player_building_flags):
            if not flag:
                state.player_building_flags[i] = True
                return state.player_tech_building_ids[i]
        if not state.player_tech_building_ids:
            return 0
        return state.player_tech_building_ids[state.rng.rand_mod(len(state.player_tech_building_ids))]

    def _write_maps(self, writer: LDFWriter, state: _State) -> None:
        writer.line(";------------------------------------------------------------")
        writer.line(";--- Map Dumps                                            ---")
        writer.line(";------------------------------------------------------------")
        writer.line("begin_maps")
        for name in ("typ", "own", "hgt", "blg"):
            writer.map_block(f"{name}_map", state.maps[name], state.width, state.height)
        writer.end_block()
        writer.line(";------------------------------------------------------------")
        writer.line(";--- End Of File                                          ---")
        writer.line(";------------------------------------------------------------")
